"""Convert the committed PII NER dataset CSV into spaCy DocBin train/dev files.

Deliberately does NOT regenerate the source CSV - the dataset generator
notebook has no random seed and produces different data on every run, so
this script (and CI) only ever consume the CSV already committed to the repo
as the reproducible source of truth.

    uv run python pii_ner/scripts/build_docbin.py
    uv run python pii_ner/scripts/build_docbin.py --csv other.csv --out-dir pii_ner
"""

from __future__ import annotations

import json
from pathlib import Path

import click
import pandas as pd
import spacy
from spacy.tokens import DocBin

_PII_NER_DIR = Path(__file__).resolve().parent.parent
# NOTE: also update the matching filename reference in README.md's
# Development section whenever a new dataset version is committed.
DEFAULT_CSV = _PII_NER_DIR / "dataset_ner_3000_v1.csv"
DEFAULT_OUT_DIR = _PII_NER_DIR
DEFAULT_TRAIN_FRACTION = 0.9
DEFAULT_RANDOM_STATE = 42  # matches pii_ner_train.ipynb exactly


def build_doc_bin(nlp: spacy.Language, dataframe: pd.DataFrame) -> DocBin:  # type: ignore
    doc_bin = DocBin()
    for _, row in dataframe.iterrows():
        doc = nlp.make_doc(row["teks"])
        ents = []
        for ent in json.loads(row["entitas"]):
            span = doc.char_span(
                ent["start"], ent["end"], label=ent["label"], alignment_mode="contract"
            )
            if span is not None:
                ents.append(span)
        doc.ents = ents
        doc_bin.add(doc)
    return doc_bin


@click.command()
@click.option(
    "--csv",
    "csv_path",
    type=click.Path(exists=True, dir_okay=False, path_type=Path),
    default=DEFAULT_CSV,
    show_default=True,
    help="Committed dataset CSV. Never regenerated by this script.",
)
@click.option(
    "--out-dir",
    type=click.Path(file_okay=False, path_type=Path),
    default=DEFAULT_OUT_DIR,
    show_default=True,
    help="Directory to write train.spacy / dev.spacy into.",
)
@click.option(
    "--train-fraction", type=float, default=DEFAULT_TRAIN_FRACTION, show_default=True
)
@click.option(
    "--random-state", type=int, default=DEFAULT_RANDOM_STATE, show_default=True
)
def main(
    csv_path: Path, out_dir: Path, train_fraction: float, random_state: int
) -> None:
    df = pd.read_csv(csv_path)
    df = df.sample(frac=1, random_state=random_state).reset_index(drop=True)
    split_idx = int(len(df) * train_fraction)
    df_train, df_dev = df.iloc[:split_idx], df.iloc[split_idx:]

    nlp = spacy.blank("xx")
    out_dir.mkdir(parents=True, exist_ok=True)
    train_path, dev_path = out_dir / "train.spacy", out_dir / "dev.spacy"
    build_doc_bin(nlp, df_train).to_disk(train_path)
    build_doc_bin(nlp, df_dev).to_disk(dev_path)

    click.echo(
        f"Total rows: {len(df)} | train: {len(df_train)} -> {train_path} "
        f"| dev: {len(df_dev)} -> {dev_path}"
    )


if __name__ == "__main__":
    main()
